default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hosimi_development

test:
  <<: *default
  database: hosimi_test

production:
  <<: *default
  database: hosimi_production
  username: <%= ENV['HOSIMI_DATABASE_USERNAME'] %>
  password: <%= ENV['HOSIMI_DATABASE_PASSWORD'] %>

cable:
  <<: *default
  database: hosimi_production
  username: <%= ENV['HOSIMI_DATABASE_USERNAME'] %>
  password: <%= ENV['HOSIMI_DATABASE_PASSWORD'] %>

queue:
  <<: *default
  database: hosimi_production
  username: <%= ENV['HOSIMI_DATABASE_USERNAME'] %>
  password: <%= ENV['HOSIMI_DATABASE_PASSWORD'] %>

cache:
  <<: *default
  database: hosimi_production
  username: <%= ENV['HOSIMI_DATABASE_USERNAME'] %>
  password: <%= ENV['HOSIMI_DATABASE_PASSWORD'] %>