default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: 127.0.0.1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: astronom_development

test:
  <<: *default
  database: astronom_test

production:
  <<: *default
  database: astronom_production
  username: <%= ENV['ASTRONOM_DATABASE_USERNAME'] %>
  password: <%= ENV['ASTRONOM_DATABASE_PASSWORD'] %>